# .github/workflows/ci.yml

name: MLOps Model CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - main
permissions:
    contents: write
    pull-requests: write

jobs:
  test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
    
      - name: Setup CML (Continuous Machine Learning)
        uses: iterative/setup-cml@v2.0.1
        

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn pandas numpy pytest joblib dvc dvc-gs
          pip install dvc[gcs]
        
      - name: Google Cloud Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA }}'
    
      - name: Pulling Data & Model using DVC
        run: |
          dvc pull

      - name: Run Tests
        run: |
          pytest -v &> output.txt 

      # - name: Model Evaluation
      #   run: |
      #     mkdir artifact_metrics
      #     python3 check_metrics.py
      
      - name: Create cml report
        run: |
          echo "# CML Test & Evaluation Report" > report.md

          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}